name: 提交课程评价
description: 按固定格式提交一条课程评价（会在审核后合并到网站）
title: "[评价] 课程名 - 老师 - 学期"
labels: ["review"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你愿意分享课程体验！
        - 建议：尽量客观、具体，避免人身攻击
        - 多老师请用 `、` 分隔；不要写“等”（系统会做清洗，但你写得规范更好）
        - 学期：请先选择“秋/春/夏”，再填写“学年”（例如 `2024-2025`）

  - type: input
    id: courseName
    attributes:
      label: 课程名称
      placeholder: 例如：Web安全技术
    validations:
      required: true

  - type: input
    id: instructors
    attributes:
      label: 任课老师
      placeholder: 例如：刘奇旭、刘潮歌
    validations:
      required: true

  - type: dropdown
    id: termSeason
    attributes:
      label: 学期（选择）
      description: 为了后续聚合一致性，学期请按“秋/春/夏”选择（同一季节跨年份会合并展示；不同季节会分开）
      options:
        - 秋（第1学期）
        - 春（第2学期）
        - 夏（第3学期）
        - 不确定
    validations:
      required: true

  - type: input
    id: academicYear
    attributes:
      label: 学年（必填）
      description: 填 `YYYY-YYYY`（例如 `2024-2025`）。如果不确定可先写 `2024-2025?`，审核时我们会再确认/修正。
      placeholder: 例如：2024-2025
    validations:
      required: true

  - type: dropdown
    id: college
    attributes:
      label: 开课学院（选择）
      description: 为了保证筛选统计一致性，请从列表中选择；如果不确定可选“（不确定/未列出）”，并在下一项补充说明（可选）
      options:
        - （不确定/未列出）
        - 人文学院
        - 外语系
        - 数学科学学院
        - 物理科学学院
        - 化学科学学院
        - 生命科学学院
        - 地球与行星科学学院
        - 资源与环境学院
        - 经济与管理学院
        - 材料科学与光电技术学院
        - 公共政策与管理学院
        - MBA
        - 教务处
        - 体育部
        - 计算机科学与技术学院
        - 电子电气与通信工程学院
        - 中丹学院
        - 国际学院
        - 本科部
        - 天文与空间科学学院
        - 工程科学学院
        - 医学院
        - 集成电路学院
        - 未来技术学院
        - 网络空间安全学院
        - 马克思主义学院
        - MPA
        - 明德讲堂
        - 现代产业学院
        - 心理学系
        - 人工智能学院
        - 纳米科学与工程学院
        - 艺术中心
        - 光电学院
        - 核科学与技术学院
        - 现代农业科学学院
        - 化学工程学院
        - 星际航行学院
        - 温州研究院
        - 大珩学院
        - 深圳先进技术与工程学院
        - 机器人与智能制造学院
        - 附件学院
        - 能源学院
        - 应急管理科学与工程学院
        - 密码学院
        - 雄安学院
        - 人居科学学院
        - MEMEM
        - 基础教育研究院
        - 玉泉书院
        - 前沿交叉科学学院
        - AI
        - MEM
        - MEMTM
    validations:
      required: false

  - type: input
    id: collegeOther
    attributes:
      label: 开课学院补充（可选）
      description: 如果上面选择了“（不确定/未列出）”，可以在这里补充你认为的学院名称（可留空）
      placeholder: 例如：某某学院/研究院
    validations:
      required: false

  - type: input
    id: credits
    attributes:
      label: 学分
      placeholder: 例如：2
    validations:
      required: true

  - type: dropdown
    id: degree
    attributes:
      label: 学位课
      options:
        - 是
        - 否
    validations:
      required: true

  - type: dropdown
    id: value
    attributes:
      label: 价值（1-5星）
      description: 这是“综合价值”评分：结合**收获/课程质量/给分体验/投入产出比**来评。建议也在“备注”里写一句你给这个分数的理由（最有帮助）。
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
    validations:
      required: true

  - type: dropdown
    id: passDifficulty
    attributes:
      label: 及格难度（1-5星，越低越容易）
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
    validations:
      required: true

  - type: dropdown
    id: highScoreDifficulty
    attributes:
      label: 高分难度（1-5星，越低越容易）
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
    validations:
      required: true

  - type: textarea
    id: remark
    attributes:
      label: 备注（最重要）
      description: 例如：上课形式/作业/考试/给分/避坑建议/适合人群
      placeholder: 请尽量具体（可换行）
    validations:
      required: true


